version: '3'
services:
  student_service:
    image: ivanipenburg/python-flask-server-generated:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://localhost:27017
    ports:
      - "8000:8000"

  mongo:
    restart: unless-stopped
    image: mongo:4
    ports:
      - "27017:27017"