name: Build Test and push
on: [push]
env:
  IMAGE_NAME: python-flask-server-generated
  REPO_NAME: ivanipenburg


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker build . -t $REPO_NAME/$IMAGE_NAME
    - name: run docker
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: docker-compose.yaml
    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: postman/collection.json
        environment: postman/environment.json
        reporters: cli
        iterationCount: 3

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}


    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$IMAGE_NAME